var seeds = { 
			"Nike": ["shoes", "sports", "sneakers", "shirts", "shorts", "bras", "socks", "running", "athletics"],
			"Equinox": ["fitness", "gym", "lift", "running", "exercise ", "stretch", "health"], 
			"Restoration": ["couch", "decorate", "home", "fabric", "design", "simple", "curtain", "lamp", "table"], 
			"Ann Taylor": ["fashion", "blouse", "pants", "dress", "wedding", "heels", "flats", "bags", "jewelry"], 
			"The Home Depot": ["garden", "tool", "renovation", "lighting", "paint", "build", "wood", "storage", "remodel"], 
			"Papyrus": ["cards", "stationary", "gift", "wrapping", "ribbon", "cards", "birthday", "wedding", "journal", "notebooks"], 
			"Brooks Brothers": ["fashion", "blouse", "blazer", "skirt", "dress", "wedding", "flats", "sweater", "tie", "shoes", "heels", "cardigan", "suit", "jacket", "shorts", "sleepwear", "swimwear", "polo"],
			"Paragon": ["sports", "outdoor", "baseball", "basketball", "boating", "cycling", "football", "golf", "hiking", "hockey", "running", "skiing", "snowboarding", "soccer", "spin", "swimming", "tennis", "triathlon", "yoga", "boots", "cycling", "golf", "hiking", "running", "sandals", "tennis"],
			 "True Religion": ["shorts", "pants", "legging", "tees", "tanks", "shirts", "sweatshirts", "bags", "scarves", "hats", "belts", "bottoms", "tops"],
			 "Fresh": ["cleanser", "mask", "moisturizer", "eye", "serum", "toner", "exfoliant", "bath", "oil", "deodorant"],
			 "Dr. Martens": ["boots", "heels", "hiking", "vintage", "waterproof", "industrial", "oxfords", "sandals", "chelsea"],
			 "Scotch and Soda": ["accessories", "fragrance", "bikinis", "blazer", "blouses", "dresses", "coats", "jackets", "jeans", "jumpsuits", "leather", "lingerie", "pants", "shoes", "shorts", "skirts", "sweaters", "tops", "shirts"],
			 "Chipotle": ["food", "mexican", "burrito", "grill", "taco", "nutrition", "salad", "chicken", "steak", "beans", "rice", "tofu", "guacamole", "salsa", "chips", "carnitas", "barbacoa", "sofritas"],
			 "Republic": ["noodle", "food", "nutrition", "dumpling", "calamari", "salmon", "sashimi", "japanese", "wonton", "fried", "salad", "vietnamese", "vegetables", "curry", "spicy", "beef", "chicken", "seafood", "asian", "thai", "padthai", "pork", "rice", "coconut"],
			 "Heartland Brewery": ["beer", "craft", "brewery", "burger", "fries", "salad", "lager", "ale", "oktoberfest", "wings", "bbq", "steak", "chicken", "sandwich", "pint", "pretzel", "fish", "chips"],
			 "Dylan’s Candy Bar": ["candy", "sweets", "chocolates", "gummy", "jelly", "lollipops", "pretzel", "cupcake", "cake", "strawberry", "raspberry", "hazelnut", "s’mores", "toffee", "caramel", "cookies", "cream"],
			 "Blue Water Grill": ["grill", "food", "wine", "cocktail", "shrimp", "brunch", "lunch", "dinner", "dessert", "hamburger", "burger", "cheese", "oysters", "lobsters", "salad", "tuna", "chicken", "japanese", "salmon", "kampachi", "tempura", "taco", "slider", "soup", "scallops", "rigatoni", "dining", "sushi"],
			 "Irvington": ["food", "lunch", "brunch", "dinner", "dining", "breakfast", "bar", "cocktail", "dessert", "wine", "beer", "rum", "whiskey", "tequila", "vodka", "soup", "salad", "fries", "burgers", "sausage", "coffee", "juice", "tuna", "chicken", "salmon", "ham", "sandwich", "lobster", "calamari", "lasagna", "bourbon", "cognac", "rye"],
			 "Starbucks": ["coffee", "mocha", "frappachino", "latte", "espresso", "tea", "beverage", "pastry", "smoothies"],
			 "Barnes & Noble": ["books", "read", "fiction", "nonfiction", "biography", "business", "mystery", "romance", "textbook"],
			 "Sephora": ["mascara", "eyeliner", "lip stick", "foundation", "concealer", "blush", "bronzer", "cleanser", "eyeshadow", "eyebrow", "tanning", "mask", "exfoliant", "nails", "hair"],
			 "Rothmans": ["fashion", "blouse", "blazer", "skirt", "dress", "wedding", "flats", "sweater", "tie", "shoes", "heels", "cardigan", "suit", "jacket", "shorts", "sleepwear", "swimwear", "polo"]
			};
